config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

resources :students
resources :instructors
resources :courses

end

app/models/class.rb
class Class < ActiveRecord::Base
belongs_to :student
belongs_to :instructor

end

app/models/course.rb
class Course < ActiveRecord::Base
belongs_to :student
belongs_to :instructor


end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
has_many :courses
has_many :students, :through => :courses
end

app/models/student.rb
class Student < ActiveRecord::Base
has_many :courses
has_many :instructors, :through => :courses


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @instructor = Instructor.find_by_id(params[:instructor_id])
    @courses = Course.all
  end

  def new
    @course = Course.new
    @students = Student.all
    @instructors = Instructor.all
  end

  def create
    @student = Student.find_by_id(params[:student_id])
    @instructor = Instructor.find_by_id(params[:instructor_id])
    @course = Course.new(course_params)
    if @course.save
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
    @student = Student.find_by_id(params[:student_id])
    @students = Student.all
    @instructor = Instructor.find_by_id(params[:instructor_id])
  end

  def edit
    @course = Course.find(params[:id])
    @student = Student.find_by_id(params[:student_id])
    @instructor = Instructor.find_by_id(params[:instructor_id])
  end

  def update
    @student = Student.find_by_id(params[:student_id])
    @instructor = Instructor.find_by_id(params[:instructor_id])
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to course_path(@course)
    else
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
  end

private
def course_params
  params.require(:course).permit(:subject, :student_id, :instructor_id)
end


end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all
  end

  def new
    @instructor = Instructor.new
    @courses = Course.all 
  end

  def create
    @course = Course.find_by_id(params[:course_id])
    @instructor = Instructor.new(instructor_params)
    @instructor.courses << @course
    if @instructor.save
      redirect_to instructor_path(@instructor)
    else
      render :new
    end
  end

  def show
    @course = Course.find_by_id(params[:course_id])
    @instructor = Instructor.find(params[:id])
  end

  def edit
    @course = Course.find_by_id(params[:course_id])
    @instructor = Instructor.find(params[:id])
  end

  def update
    @course = Course.find_by_id(params[:course_id])
    @instructor = Instructor.find(params[:id])
    @instructor.courses << @course
    if @instructor.update(instructor_params)
      redirect_to instructor_path(@instructor)
    else
      render :edit
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
  end

  private
  def instructor_params
    params.require(:instructor).permit(:first_name, :last_name)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
    @courses = Course.all
  end

  def create
    @course = Course.find_by_id(params[:course_id])
    @student = Student.new(student_params)
    @student.courses << @course
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def show
    @course = Course.find_by_id(params[:course_id])
    @student = Student.find(params[:id])
  end

  def edit
    @course = Course.find_by_id(params[:course_id])
    @student = Student.find(params[:id])
  end

  def update
    @course = Course.find_by_id(params[:course_id])
    @student = Student.find(params[:id])
    @student.courses << @course
    if @student.update(student_params)
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/edit.html.erb
<%= form_for @course do |f| %>

<%= collection_select @instructor, :instructor_id, Instructor.all, :id, :first_name, :prompt => 'Select Instructor', :multiple => true %>

<%= collection_select @student, :student_id, Student.all, :id, :first_name, :prompt => 'Select Student', :multiple => true %>

<%= f.label :subject %>
<%= f.text_field :subject %>

<%= f.submit %>

<% end %>

app/views/courses/index.html.erb
<%= link_to 'Home', root_path %>

<%= link_to 'Add New Course', new_course_path %>

<h2> COURSES </h2>
<table>
  <tr>
    <th>
      SUBJECT
    </th>

  </tr>

  <% @courses.each do |course| %>
  <tr>
    <td>
      <%= link_to {link_to(course.subject, course)} %> <br>
    </td>
    <td>
      <%= course.instructor %> <br>

    </td>
  </tr>
</table>


 <% end %>

app/views/courses/new.html.erb
<%= form_for @course do |f| %>

<%= collection_select @instructor, :instructor_id, Instructor.all, :id, :first_name, :prompt => 'Select Instructor', :multiple => true %>

<%= collection_select @student, :student_id, Student.all, :id, :first_name, :prompt => 'Select Student', :multiple => true %>

<%= f.label :subject %>
<%= f.text_field :subject %>

<%= f.submit %>

<% end %>

app/views/courses/show.html.erb
<h1> Course Subject:  <%= @course.subject %> </h1>

<%= link_to 'Courses', courses_path %>
<%= link_to 'Edit Course', edit_course_path(@course) %>
<%= link_to("Delete Course", @course, :method => :delete, :class => 'action', data: {confirm: "Are you sure?"}) %>


<h2> Class Instructor: <%= @course.instructor %> </h2>

<%= @course.students %>

app/views/instructors/edit.html.erb
<h1> edit yourself </h1>

<%= form_for @instructor do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= collection_select @course, :course_id, Course.all, :id, :subject, :prompt => 'Select Course', :multiple => true %>


<%= f.submit %>

<% end %>

app/views/instructors/index.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Add New Instructor', new_instructor_path %>

<h2> INSTRUCTORS </h2>
<table>
  <tr>
    <th>
      FIRST NAME
    </th>
    <th>
      LAST NAME
    </th>
  </tr>

  <% @instructors.each do |instructor| %>
  <tr>
    <td>
      <%= link_to {link_to(instructor.first_name, instructor)} %> <br>
    </td>
    <td>
    </td>
  </tr>
</table>


 <% end %>

app/views/instructors/new.html.erb
<%= form_for @instructor do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= collection_select @course, :course_id, Course.all, :id, :subject, :prompt => 'Select Course', :multiple => true %>


<%= f.submit %>

<% end %>

app/views/instructors/show.html.erb
<h2> COURSES for Instructor: <%= @instructor.first_name %> <%= @instructor.last_name %> </h2>

<hr>
<%= link_to 'Edit Yourself', edit_instructor_path %>
<%= link_to("Delete Yourself", @instructor, :method => :delete, :class => 'action', data: {confirm: "Are you sure?"}) %>

<table>
  <tr>
    <th>
      COURSE SUBJECT
    </th>
  </tr>

  <tr>
    <td>
      <% @instructor.courses.each do |course| %>
      <%= course.subject %> <br>
      <% end %>

    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>G6Assessment3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1> edit yourself </h1>

<%= form_for @student do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= collection_select @course, :course_id, Course.all, :id, :subject, :prompt => 'Select Course', :multiple => true %>


<%= f.submit %>

<% end %>

app/views/students/index.html.erb
<%= link_to 'HOME', root_path %>
<%= link_to 'NEW STUDENT', new_student_path %>
 <hr>


<h2> STUDENTS </h2>
<table>
  <tr>
    <th>
      FIRST NAME
    </th>
    <th>
      LAST NAME
    </th>
  </tr>

  <% @students.each do |student| %>
  <tr>
    <td>
      <%= link_to {link_to(student.first_name, student)} %> <br>
    </td>
    <td>
    </td>
  </tr>
</table>


 <% end %>

app/views/students/new.html.erb
<%= form_for @student do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= collection_select @course, :course_id, Course.all, :id, :subject, :prompt => 'Select Course', :multiple => true %>


<%= f.submit %>

<% end %>

app/views/students/show.html.erb
<h2> Courses for Student: <%= @student.first_name %> <%= @student.last_name %>
 </h2>

<hr>

<%= link_to 'Edit Yourself', edit_student_path %>
<%= link_to("Delete Yourself", @student, :method => :delete, :class => 'action', data: {confirm: "Are you sure?"}) %>

 <table>
   <tr>
     <th>
       COURSE SUBJECT
     </th>
   </tr>

   <tr>
     <td>
       <% @student.courses.each do |course| %>
       <%= course.subject %> <br>
       <% end %>
     </td>
   </tr>
 </table>

app/views/welcome/index.html.erb
<%= link_to 'Students', students_path %>

<%= link_to 'Instructors', instructors_path %>

<%= link_to 'Courses', courses_path %>